name: custom_input_formatter
description: "A Flutter package providing customizable input formatters for amounts and numbers with group separators."
version: 2.0.1
homepage: https://github.com/inossan-dev/custom_input_formatter.git

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
