name: custom_input_formatter
description: "A Flutter package providing customizable input formatters for amounts and numbers with group separators."
version: 1.0.0
homepage: https://github.com/inossan-dev/custom_input_formatter.git
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' identifies the class that the plugin's
  # platform-specific code should inherit from in order to work.
  plugin:
    platforms:
      android:
        package: com.example.custom_input_formatter
        pluginClass: CustomInputFormatterPlugin
      ios:
        pluginClass: CustomInputFormatterPlugin